const cards=[['体育代理','体育业务合作与推广方向'],['代理招商','合作申请、渠道与流程'],['代理佣金','佣金核算与结算说明'],['代理政策','有效业绩与合作规范'],['真人电子','业务方向与合作信息'],['合作指南','从了解政策到建立合作']];
const articles=[['代理合作前，先确认哪几件事？','合作指南'],['代理佣金通常看哪些数据？','佣金政策'],['如何规划长期推广渠道？','经营经验']];
export default function Home(){return <main>
<header><div className="nav"><a className="brand" href="/">KAIYUN<span>.SI</span></a><nav><a href="/">首页</a><a href="#business">代理合作</a><a href="#policy">佣金政策</a><a href="#faq">常见问题</a></nav><div className="navActions"><a className="registerBtn" href="http://5257y.com" target="_blank" rel="noopener noreferrer">立即注册</a><a className="serviceBtn" href="https://t.me/caijin101" target="_blank" rel="noopener noreferrer">彩金客服</a></div></div></header>
<section className="hero"><div className="glow"></div><div className="wrap heroGrid"><div><p className="eyebrow">KAIYUN · PARTNERSHIP</p><h1>代理合作，<br/><em>做得更清楚。</em></h1><p className="lead">整理代理合作、佣金政策、推广方向与经营经验。把复杂的信息，变成容易理解的合作指南。</p><div className="actions"><a className="btn" href="#business">了解代理合作</a><a className="ghost" href="https://t.me/a8802717">联系锦鲤 →</a></div><div className="stats"><span><b>6+</b>合作主题</span><span><b>长期</b>内容更新</span><span><b>一站式</b>信息整理</span></div></div><div className="visual"><div className="orb"></div><div className="pitch"><i></i><strong>K</strong><small>SPORTS · BUSINESS · GROWTH</small></div></div></div></section>
<section id="business" className="light"><div className="wrap"><p className="eyebrow blue">COOPERATION</p><h2>核心合作内容</h2><p className="sub">从注册、政策到推广，把常用合作信息集中在一个地方。</p><div className="grid">{cards.map((x,i)=><article className="card" key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p><a href="#contact">了解更多 →</a></article>)}</div></div></section>
<section id="policy" className="dark"><div className="wrap split"><div><p className="eyebrow">POLICY & SETTLEMENT</p><h2>佣金 · 政策 · 结算</h2><p className="sub darksub">合作前先把规则说清楚。佣金比例、有效业绩和结算周期，应以双方当前确认的合作方案为准。</p><a className="btn" href="#contact">咨询当前合作政策</a></div><div className="policy"><div><b>01</b><h3>佣金政策</h3><p>了解核算逻辑与适用比例。</p></div><div><b>02</b><h3>有效业绩</h3><p>确认纳入核算的数据范围。</p></div><div><b>03</b><h3>结算周期</h3><p>明确周期、数据与结算条件。</p></div></div></div></section>
<section id="insights" className="light"><div className="wrap"><p className="eyebrow blue">JINLI INSIGHTS</p><h2>锦鲤说代理</h2><p className="sub">代理经验、渠道流量、经营复盘与行业观察。</p><div className="articles">{articles.map(x=><article><small>{x[1]}</small><h3>{x[0]}</h3><p>用实际业务视角整理关键问题，减少无效沟通和重复试错。</p><a href="#contact">阅读主题 →</a></article>)}</div></div></section>
<section id="faq" className="faq"><div className="wrap"><p className="eyebrow">FAQ</p><h2>常见问题</h2>{[['如何了解代理合作？','先确认业务方向、推广渠道和合作需求，再沟通当前适用的合作方案。'],['佣金如何计算？','不同合作模式可能不同，应以当前确认的佣金比例、有效业绩及结算规则为准。'],['可以推广哪些方向？','可根据实际合作范围了解体育、真人、电子等方向。'],['合作政策会调整吗？','可能根据业务和合作方案调整，实际执行以当期双方确认内容为准。']].map(x=><details><summary>{x[0]}<b>＋</b></summary><p>{x[1]}</p></details>)}</div></section>
<section id="contact" className="cta"><div className="wrap"><p className="eyebrow">WORK WITH JINLI</p><h2>想进一步了解代理合作？</h2><p>联系锦鲤，了解当前合作方式与业务方向。</p><a className="btn gold" href="https://t.me/a8802717">Telegram：@a8802717</a></div></section>
<footer><div className="wrap foot"><div><a className="brand" href="/">KAIYUN<span>.SI</span></a><p>代理合作 · 行业资讯 · 长期内容</p></div><div><b>内容</b><a href="#business">代理合作</a><a href="#policy">佣金政策</a><a href="#insights">行业资讯</a></div><div><b>联系</b><a href="https://t.me/a8802717">Telegram</a><span>@a8802717</span></div></div><div className="copy">© 2026 KAIYUN.SI · 本站仅提供合作与行业信息，具体政策以实际确认内容为准。</div></footer>
</main>}
